language: node_js
node_js:
- '10'
cache: yarn
env:
  secure: TnWkxmqffUq5rAUPrOyxhBKhPZSRKDQMRE4x8yaKbtbbguX3uMgdwvngWc2TMuO0/wbfvbOls736SHQESQKt5qJXnLJDpIYSL/swkQJBQwPVNkmusaWEU4P3J6S+ZXI7dR04T6D9rkdrvAb2lZ6hCZ5mDN5nNBx3VlQ4654RlEFV1EoeGDPW4DZBGCinLV7tMfMki+vibkwOmLnObpcTRKWvT8q+7HvmjTtnSd3vE2NJQvN60DscI8ADqmLyQ/H5HOk13f1JqjItVfBRzt4JEGCbsJzS3GzscR7Crhht3YNGr8DE+ZutNR8GiSnE2e5sG7IQWz99ZixavfNh8RDg6gX12kpJ3n2G6pZERYlf54SENhX/39hAW+hIIM6GWaV4xIyKIdwhPmzWzaQQYgYFXYNpX6GPMA3FBi7mNCSEbnrW2dNjlLACANu8qtdpRv2l8UxnC+K0eHg9TQDnnzS87ToL2sRz2DOrB9bC2/FcW4GbM1ObS2yPres0TP0WP0S/v4IseyR6RUg4kBUhS0WlBshUO9DT2V4fUJYT1Eu6Uc+ef9kMtFlfmNoF6SSV/16N+D+5azlrFeIAupAsy6sdXBDyt8TEe5qIAyjiGtsCpFXtBwtkgaWBzSm8B0E4osgE7pKM9MlbY6/d8Vlp33VYB+Afzav1pdv41vEfFNEhX3I=
script:
- npm run build:staging
notifications:
  email:
    on_failure: change
on_success: change
before_install:
- openssl aes-256-cbc -K $encrypted_172b5ce8d004_key -iv $encrypted_172b5ce8d004_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
- chmod +x .travis/deploy.sh
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan $DOKKU_SERVER >> ~/.ssh/known_hosts
- |
  if [[ ${TRAVIS_PULL_REQUEST} == "false" ]] && [[ ${TRAVIS_BRANCH} == "dev" ]]; then
    git remote add deploy dokku@$DOKKU_SERVER:$DOKKU_DEV_APP
  fi
- |
  if [[ ${TRAVIS_PULL_REQUEST} == "false" ]] && [[ ${TRAVIS_BRANCH} == "master" ]]; then
    git remote add deploy dokku@$DOKKU_SERVER:$DOKKU_PRODUCTION_APP
  fi
- git config --global push.default simple
after_success:
- bash ./.travis/deploy.sh ${TRAVIS_PULL_REQUEST} ${TRAVIS_BRANCH}
