name: Deploy dive preview 

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
  
    - run: yarn install
    - name: Deploy dive preview
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn ng -- deploy --base-href=/dive-frontend-preview/ --name="Github Actions" --email="" --no-silent
